### PR TITLE
test

### PR DESCRIPTION
**Pull request by kawakibi**
## REMINDER
It Seems you want to merge into **MASTER BRANCH**
* **DEPLOY IT** To staging. **TEST** **TEST** **TEST** !
* BEWARE OF static files versioning.
* Please do not **FORGET merging**  back into **DEVELOPMENT** after Release
* Delete old release Branch

`this message was posted by bot, if you have any question you can contact dev@kaskusnetworks.com`

### CODE REVIEW

**Comment by kawakibi** [comment]
Me too

**Comment by kawakibi** [comment]
merging cok

**Comment by kawakibi** [comment]
Image of Pertamax
## REMINDER
It Seems you want to merge into **MASTER BRANCH**
* **DEPLOY IT** To staging. **TEST** **TEST** **TEST** !
* BEWARE OF static files versioning.
* Please do not **FORGET merging**  back into **DEVELOPMENT** after Release
* Delete old release Branch

`this message was posted by bot, if you have any question you can contact dev@kaskusnetworks.com`

**Comment by kawakibi** [comment]
## REMINDER
It Seems you want to merge into **MASTER BRANCH**
* **DEPLOY IT** To staging. **TEST** **TEST** **TEST** !
* BEWARE OF static files versioning.
* Please do not **FORGET merging**  back into **DEVELOPMENT** after Release
* Delete old release Branch

`this message was posted by bot, if you have any question you can contact dev@kaskusnetworks.com`
Image of Pertamax

**Comment by kkdeveng** [comment]
ke merged coy..../compare/development...master

**Comment by kkdeveng** [comment]
ke merged coy..../compare/development...kawakibi-patch-1

**Comment by kkdeveng** [comment]
ke merged coy....kawakibi/kawakibi.github.io/compare/development...kawakibi-patch-1

**Comment by kkdeveng** [comment]
ke merged coy....

**Comment by kkdeveng** [comment]
ke merged coy....

**Comment by kawakibi** [comment]
[link](https://github.com/kawakibi/kawakibi.github.io/compare/development...kawakibi-patch-1)

**Comment by kkdeveng** [comment]
ke merged coy....[link](http://google.com/.../asd)

**Comment by kkdeveng** [comment]
ke merged coy....[link](https://github.com/kawakibi/kawakibi.github.io/compare/development...kawakibi-patch-1)

**Comment by kkdeveng** [comment]
Image of selamat
				Image of selamat
**Dont forget to Merging Back**

Here is [link](https://github.com/kawakibi/kawakibi.github.io/compare/development...kawakibi-patch-1) for you Image of sip

**Comment by kkdeveng** [comment]
Image of selamatImage of selamat
# **Dont forget to Merging Back**

Here is shorcut [link](https://github.com/kawakibi/kawakibi.github.io/compare/development...kawakibi-patch-1) for you 

Image of sip
Image of sip

**Pull request merged**
